// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accelerometerTrainingFieldNames          = builder.RawFieldNames(&AccelerometerTraining{}, true)
	accelerometerTrainingRows                = strings.Join(accelerometerTrainingFieldNames, ",")
	accelerometerTrainingRowsExpectAutoSet   = strings.Join(stringx.Remove(accelerometerTrainingFieldNames, "create_time", "update_time"), ",")
	accelerometerTrainingRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(accelerometerTrainingFieldNames, "id", "create_time", "update_time"))
)

type (
	accelerometerTrainingModel interface {
		Insert(ctx context.Context, data *AccelerometerTraining) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*AccelerometerTraining, error)
		Update(ctx context.Context, data *AccelerometerTraining) error
		Delete(ctx context.Context, id string) error
	}

	defaultAccelerometerTrainingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AccelerometerTraining struct {
		Id         string    `db:"id"` // user id if list not empty
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		List       string    `db:"list"`
		Data       string    `db:"data"` // use float 32 array
	}
)

func newAccelerometerTrainingModel(conn sqlx.SqlConn) *defaultAccelerometerTrainingModel {
	return &defaultAccelerometerTrainingModel{
		conn:  conn,
		table: `"public"."accelerometer_training"`,
	}
}

func (m *defaultAccelerometerTrainingModel) Insert(ctx context.Context, data *AccelerometerTraining) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, accelerometerTrainingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.List, data.Data)
	return ret, err
}

func (m *defaultAccelerometerTrainingModel) FindOne(ctx context.Context, id string) (*AccelerometerTraining, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", accelerometerTrainingRows, m.table)
	var resp AccelerometerTraining
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccelerometerTrainingModel) Update(ctx context.Context, data *AccelerometerTraining) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, accelerometerTrainingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.List, data.Data)
	return err
}

func (m *defaultAccelerometerTrainingModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAccelerometerTrainingModel) tableName() string {
	return m.table
}
