// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	actFieldNames          = builder.RawFieldNames(&Act{}, true)
	actRows                = strings.Join(actFieldNames, ",")
	actRowsExpectAutoSet   = strings.Join(stringx.Remove(actFieldNames, "create_time", "update_time"), ",")
	actRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(actFieldNames, "id", "create_time", "update_time"))
)

type (
	actModel interface {
		Insert(ctx context.Context, data *Act) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Act, error)
		Update(ctx context.Context, data *Act) error
		Delete(ctx context.Context, id int64) error
	}

	defaultActModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Act struct {
		Id         int64     `db:"id"`
		Name       string    `db:"name"`
		Unit       string    `db:"unit"`
		Detail     string    `db:"detail"`
		Meaning    string    `db:"meaning"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		Author     string    `db:"author"`
		UseCounter int64     `db:"use_counter"`
	}
)

func newActModel(conn sqlx.SqlConn) *defaultActModel {
	return &defaultActModel{
		conn:  conn,
		table: `"public"."act"`,
	}
}

func (m *defaultActModel) Insert(ctx context.Context, data *Act) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, actRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Unit, data.Detail, data.Meaning, data.Author, data.UseCounter)
	return ret, err
}

func (m *defaultActModel) FindOne(ctx context.Context, id int64) (*Act, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", actRows, m.table)
	var resp Act
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActModel) Update(ctx context.Context, data *Act) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, actRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Unit, data.Detail, data.Meaning, data.Author, data.UseCounter)
	return err
}

func (m *defaultActModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultActModel) tableName() string {
	return m.table
}
