// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	heartbeatAudioHeartbeatFieldNames          = builder.RawFieldNames(&HeartbeatAudioHeartbeat{}, true)
	heartbeatAudioHeartbeatRows                = strings.Join(heartbeatAudioHeartbeatFieldNames, ",")
	heartbeatAudioHeartbeatRowsExpectAutoSet   = strings.Join(stringx.Remove(heartbeatAudioHeartbeatFieldNames, "create_time", "update_time"), ",")
	heartbeatAudioHeartbeatRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(heartbeatAudioHeartbeatFieldNames, "id", "create_time", "update_time"))
)

type (
	heartbeatAudioHeartbeatModel interface {
		Insert(ctx context.Context, data *HeartbeatAudioHeartbeat) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*HeartbeatAudioHeartbeat, error)
		Update(ctx context.Context, data *HeartbeatAudioHeartbeat) error
		Delete(ctx context.Context, id string) error
	}

	defaultHeartbeatAudioHeartbeatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HeartbeatAudioHeartbeat struct {
		Id         string    `db:"id"` // user id if list not empty
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		Data       string    `db:"data"` // use float 32 array
	}
)

func newHeartbeatAudioHeartbeatModel(conn sqlx.SqlConn) *defaultHeartbeatAudioHeartbeatModel {
	return &defaultHeartbeatAudioHeartbeatModel{
		conn:  conn,
		table: `"public"."heartbeat_audio_heartbeat"`,
	}
}

func (m *defaultHeartbeatAudioHeartbeatModel) Insert(ctx context.Context, data *HeartbeatAudioHeartbeat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, heartbeatAudioHeartbeatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Data)
	return ret, err
}

func (m *defaultHeartbeatAudioHeartbeatModel) FindOne(ctx context.Context, id string) (*HeartbeatAudioHeartbeat, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", heartbeatAudioHeartbeatRows, m.table)
	var resp HeartbeatAudioHeartbeat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHeartbeatAudioHeartbeatModel) Update(ctx context.Context, data *HeartbeatAudioHeartbeat) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, heartbeatAudioHeartbeatRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Data)
	return err
}

func (m *defaultHeartbeatAudioHeartbeatModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHeartbeatAudioHeartbeatModel) tableName() string {
	return m.table
}
