// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	heartbeatAudioOggFieldNames          = builder.RawFieldNames(&HeartbeatAudioOgg{}, true)
	heartbeatAudioOggRows                = strings.Join(heartbeatAudioOggFieldNames, ",")
	heartbeatAudioOggRowsExpectAutoSet   = strings.Join(stringx.Remove(heartbeatAudioOggFieldNames, "create_time", "update_time"), ",")
	heartbeatAudioOggRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(heartbeatAudioOggFieldNames, "id", "create_time", "update_time"))
)

type (
	heartbeatAudioOggModel interface {
		Insert(ctx context.Context, data *HeartbeatAudioOgg) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*HeartbeatAudioOgg, error)
		Update(ctx context.Context, data *HeartbeatAudioOgg) error
		Delete(ctx context.Context, id string) error
	}

	defaultHeartbeatAudioOggModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HeartbeatAudioOgg struct {
		Id         string    `db:"id"` // user id if list not empty
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		Data       string    `db:"data"` // file data
	}
)

func newHeartbeatAudioOggModel(conn sqlx.SqlConn) *defaultHeartbeatAudioOggModel {
	return &defaultHeartbeatAudioOggModel{
		conn:  conn,
		table: `"public"."heartbeat_audio_ogg"`,
	}
}

func (m *defaultHeartbeatAudioOggModel) Insert(ctx context.Context, data *HeartbeatAudioOgg) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, heartbeatAudioOggRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Data)
	return ret, err
}

func (m *defaultHeartbeatAudioOggModel) FindOne(ctx context.Context, id string) (*HeartbeatAudioOgg, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", heartbeatAudioOggRows, m.table)
	var resp HeartbeatAudioOgg
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHeartbeatAudioOggModel) Update(ctx context.Context, data *HeartbeatAudioOgg) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, heartbeatAudioOggRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Data)
	return err
}

func (m *defaultHeartbeatAudioOggModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHeartbeatAudioOggModel) tableName() string {
	return m.table
}
