// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	measureIndexHistoryFieldNames          = builder.RawFieldNames(&MeasureIndexHistory{}, true)
	measureIndexHistoryRows                = strings.Join(measureIndexHistoryFieldNames, ",")
	measureIndexHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(measureIndexHistoryFieldNames, "create_time", "update_time"), ",")
	measureIndexHistoryRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(measureIndexHistoryFieldNames, "id", "create_time", "update_time"))
)

type (
	measureIndexHistoryModel interface {
		Insert(ctx context.Context, data *MeasureIndexHistory) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*MeasureIndexHistory, error)
		Update(ctx context.Context, data *MeasureIndexHistory) error
		Delete(ctx context.Context, id string) error
	}

	defaultMeasureIndexHistoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MeasureIndexHistory struct {
		Id         string    `db:"id"` // user id
		List       string    `db:"list"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newMeasureIndexHistoryModel(conn sqlx.SqlConn) *defaultMeasureIndexHistoryModel {
	return &defaultMeasureIndexHistoryModel{
		conn:  conn,
		table: `"public"."measure_index_history"`,
	}
}

func (m *defaultMeasureIndexHistoryModel) Insert(ctx context.Context, data *MeasureIndexHistory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, measureIndexHistoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.List)
	return ret, err
}

func (m *defaultMeasureIndexHistoryModel) FindOne(ctx context.Context, id string) (*MeasureIndexHistory, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", measureIndexHistoryRows, m.table)
	var resp MeasureIndexHistory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMeasureIndexHistoryModel) Update(ctx context.Context, data *MeasureIndexHistory) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, measureIndexHistoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.List)
	return err
}

func (m *defaultMeasureIndexHistoryModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMeasureIndexHistoryModel) tableName() string {
	return m.table
}
