// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	traceItemFieldNames          = builder.RawFieldNames(&TraceItem{}, true)
	traceItemRows                = strings.Join(traceItemFieldNames, ",")
	traceItemRowsExpectAutoSet   = strings.Join(stringx.Remove(traceItemFieldNames, "create_time", "update_time"), ",")
	traceItemRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(traceItemFieldNames, "id", "create_time", "update_time"))
)

type (
	traceItemModel interface {
		Insert(ctx context.Context, data *TraceItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TraceItem, error)
		Update(ctx context.Context, data *TraceItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTraceItemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TraceItem struct {
		Id         int64     `db:"id"`
		UserId     string    `db:"user_id"`
		ActId      int64     `db:"act_id"`
		MeasureId  int64     `db:"measure_id"`
		Value      float64   `db:"value"`       // act value or measured value
		CreateTime time.Time `db:"create_time"` // create time
		Memo       string    `db:"memo"`        // annotation
		Time       time.Time `db:"time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTraceItemModel(conn sqlx.SqlConn) *defaultTraceItemModel {
	return &defaultTraceItemModel{
		conn:  conn,
		table: `"public"."trace_item"`,
	}
}

func (m *defaultTraceItemModel) Insert(ctx context.Context, data *TraceItem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, traceItemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.ActId, data.MeasureId, data.Value, data.Memo, data.Time)
	return ret, err
}

func (m *defaultTraceItemModel) FindOne(ctx context.Context, id int64) (*TraceItem, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", traceItemRows, m.table)
	var resp TraceItem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTraceItemModel) Update(ctx context.Context, data *TraceItem) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, traceItemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.ActId, data.MeasureId, data.Value, data.Memo, data.Time)
	return err
}

func (m *defaultTraceItemModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTraceItemModel) tableName() string {
	return m.table
}
